### ISSUE TITLE
carousel and page not work after deploying the maven generated build

### ISSUE THREAD

**Issue by haboy** [AdobeAtAdobe/aem-spa-example#1]
Hi ,

We are Adobe platinum support customer (Shaklee Corp) and is trying to build a spa file with angular+sightly based on aem6.1
1. When building the zip package, it reports nexus.bsl.eur.adobe.com is not resolved which caused the build fail.
2. After deploying the zip , there is no place for the page to include the carousel ( I think the hero_carousel component) and could not even use the component correctly.
3. Even I used the standard carousel component  under general group of aem6.1 sidekick, I could still not use the carousel to show the pic or pages I chose correctly under classic UI. it just showed the emply component.
email you could also reach me @ albertzhang-contractor@shaklee.com
Best regards
Albert

**Comment by dbenge** [comment]
Thanks for reporting this.  I will look into these issues.

Can you clarify #2 more?  There is no place on what page?  Are you talking about my Angular based carousel component found at apps/aaa/teamsite/components/work/hero_carousel ?  
That component can be found on /content/teamsite/work/communities page in the code base IG http://www.adobeatadobe.com/content/teamsite/work/communities.html
Or are you talking about something different?

**Comment by haboy** [comment]
Hi David ,

Yes I am talking about the hero carousel component which is not working after i put it in the page .
How to use that ?

Best regards
Albert

从三星移动设备发送

-------- 原始邮件 --------
发件人： David Benge notifications@github.com
日期:08-08-2015  01:29  (GMT+08:00)
收件人： AdobeAtAdobe/aem-spa-example aem-spa-example@noreply.github.com
抄送： haboy haboy5258@hotmail.com
主题： Re: [aem-spa-example] carousel and page not work after deploying the maven generated build (#1)

Thanks for reporting this.  I will look into these issues.

Can you clarify #2 more?  There is no place on what page?  Are you talking about my Angular based carousel component found at apps/aaa/teamsite/components/work/hero_carousel ?
That component can be found on /content/teamsite/work/communities page in the code base IG http://www.adobeatadobe.com/content/teamsite/work/communities.html
Or are you talking about something different?

---

**Comment by dbenge** [comment]
There is a problem with showing edit dialogs in the Touch UI when the component is loaded inline and not in a parsys.  If the component has a drag and drop target you can get it to show by putting in the cc-dd-xxxx class.  But there is still an open issue with other components that don't have a DnD target.  Checking with engineering on a fix for that.
